name: login_component
description: componente para login da dragon
version: 0.0.1
author: Marcelo Garcia
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_picker:
  expand_widget: ^0.2.0+2
  statusbar: ^1.1.0
  transparent_image: ^1.0.0
  dots_indicator: ^1.0.0
  photo_view: ^0.5.0
  cached_network_image: ^1.1.1
  url_launcher: ^5.2.3
  bloc: ^0.15.0
  bloc_pattern: ^2.3.2
  dio: ^2.1.13
  rxdart: ^0.22.2
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  flutter_masked_text: ^0.8.0
  expandable: ^3.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
